mipa_session_mipa_user:
    resource: "@MipaSessionBundle/Resources/config/routing/users.yml"
    prefix:   /users

mipa_session_homepage:
    pattern:  /login
    defaults: { _controller: MipaSessionBundle:Default:index }

mipa_session_logout:
    pattern:  /logout
    defaults: { _controller: MipaSessionBundle:Default:logout }
