mipa_session_mipa_user:
    resource: "@MipaSessionBundle/Resources/config/routing/users.yml"
    prefix:   /users

mipa_session_homepage:
    path:     /hello/{name}
    defaults: { _controller: MipaSessionBundle:Default:index }
